#!/bin/sh

exists=0
echo "do a check for .cs files in change set"
while read status file; do
    if [ "${file: -3}" == ".cs" ] ; then
        exists=1
        echo "find .cs file"
        break
    fi
done <<<$(git diff --cached --name-status)

echo $exists
if [[ $exists -eq 0 ]] ; then
    exit 0
else
    echo "exists .cs file, so build the project"
fi

echo "dotnet build"
dotnet clean; dotnet build
rc=$?

if [[ $rc != 0 ]] ; then
    echo "Build failed"
    exit $rc
fi

echo "dotnet test"
dotnet test

rc=$?

if [[ $rc != 0 ]] ; then
    echo "Tests failed"
    exit $rc
fi

exit 0
