#!/bin/sh

echo "dotnet build"

dotnet clean; dotnet build
rc=$?

if [[ $rc != 0 ]] ; then
    echo "Build failed"
    exit $rc
fi

echo "dotnet test"
dotnet test

rc=$?

if [[ $rc != 0 ]] ; then
    echo "Tests failed"
    exit $rc
fi

exit 0